-- Permanent bans, timed restaurant suspensions, and restaurant subscriptions.
--
-- Bans: a banned person can never log in again, and their email can't be used for a new account. A banned
-- restaurant is taken off the site for good (its owner is banned too). Admins can lift a ban made by mistake.
--
-- Restaurant suspensions now last a set number of days, like account suspensions: the every-minute sweep
-- approves the restaurant again when suspended_until passes. (Suspensions made before this have no end date and
-- last until an admin reinstates the restaurant.)
--
-- Subscriptions: restaurants pay $15 a month or $150 a year (prices are settings). The first 50 restaurants that
-- are approved are Founding Partners and use Bite Wise free for as long as they stay partners. Paid plans renew
-- automatically unless the restaurant turns auto-renewal off; the app charges the saved card (src/lib/subscriptions.ts).
-- When a renewal payment fails, the restaurant has 7 days to update its card before its plan lapses.
-- An approved restaurant needs a plan (founding or paid) to post offers.

alter table public.restaurants add column suspended_until timestamptz;

create type public.subscription_plan as enum ('founding', 'monthly', 'annual');
create type public.subscription_status as enum ('active', 'past_due', 'expired');

create table public.restaurant_subscriptions (
  restaurant_id bigint primary key references public.restaurants (id) on delete cascade,
  plan public.subscription_plan not null,
  -- The plan charged at the next renewal (a restaurant can switch between monthly and annual from then on).
  renew_plan public.subscription_plan,
  status public.subscription_status not null default 'active',
  founding_number integer unique check (founding_number > 0),
  auto_renew boolean not null default true,
  price_cents integer not null default 0 check (price_cents >= 0),
  current_period_start timestamptz,
  current_period_end timestamptz,
  customer_ref text,
  card_ref text,
  card_label text not null default '',
  last_payment_error text not null default '',
  retry_at timestamptz,
  renewing_at timestamptz,
  reminder_sent_for timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (plan = 'founding' or current_period_end is not null)
);

create table public.subscription_payments (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  plan public.subscription_plan not null,
  amount_cents integer not null check (amount_cents > 0),
  status text not null check (status in ('paid', 'failed')),
  period_start timestamptz,
  period_end timestamptz,
  invoice_number text unique,
  transaction_id text not null default '',
  card_label text not null default '',
  error text not null default '',
  created_at timestamptz not null default now()
);
create index subscription_payments_restaurant_idx on public.subscription_payments (restaurant_id, created_at desc);

-- Invoice numbers for paid subscription payments: BW-SUB-000001, ...
create sequence public.subscription_invoice_seq;
create function public.next_subscription_invoice() returns text
language sql security definer set search_path = public as $$
  select 'BW-SUB-' || lpad(nextval('public.subscription_invoice_seq')::text, 6, '0');
$$;

alter table public.restaurant_subscriptions enable row level security;
alter table public.subscription_payments enable row level security;
-- Owners and admins can read; only the server (service role) writes.
create policy "owners and admins read subscriptions" on public.restaurant_subscriptions for select to authenticated
  using (restaurant_id = (select public.my_restaurant_id()) or (select public.is_admin()));
create policy "owners and admins read subscription payments" on public.subscription_payments for select to authenticated
  using (restaurant_id = (select public.my_restaurant_id()) or (select public.is_admin()));

insert into public.settings (key, value) values
  ('subscription_monthly_cents', '1500'),
  ('subscription_annual_cents', '15000'),
  ('founding_spots', '50')
on conflict (key) do nothing;

-- True when the restaurant may post offers: a Founding Partner, a paid plan that hasn't run out, or a failed
-- renewal still inside its 7-day grace period. Auto-renewing plans also get 7 days while the renewal is charged.
create function public.restaurant_plan_ok(p_restaurant_id bigint) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.restaurant_subscriptions s
    where s.restaurant_id = p_restaurant_id
      and (s.plan = 'founding'
        or (s.status = 'active' and s.current_period_end + case when s.auto_renew then interval '7 days' else interval '0' end > now())
        or (s.status = 'past_due' and s.current_period_end + interval '7 days' > now()))
  );
$$;

-- Makes the restaurant a Founding Partner if it has no plan yet and one of the free spots (setting founding_spots)
-- is left. Returns its founding number, or null. Called by the app when a restaurant is approved.
create function public.claim_founding_spot(p_restaurant_id bigint) returns integer
language plpgsql security definer set search_path = public as $$
declare
  spots integer := coalesce((select (value #>> '{}')::integer from public.settings where key = 'founding_spots'), 50);
  existing public.restaurant_subscriptions;
  taken integer;
  n integer;
begin
  perform pg_advisory_xact_lock(hashtext('bitewise_founding_spots'));
  select * into existing from public.restaurant_subscriptions where restaurant_id = p_restaurant_id;
  if existing.restaurant_id is not null then
    return existing.founding_number;
  end if;
  select count(*) into taken from public.restaurant_subscriptions where founding_number is not null;
  if taken >= spots then
    return null;
  end if;
  select coalesce(max(founding_number), 0) + 1 into n from public.restaurant_subscriptions;
  insert into public.restaurant_subscriptions (restaurant_id, plan, status, founding_number, auto_renew, price_cents)
  values (p_restaurant_id, 'founding', 'active', n, false, 0);
  return n;
end;
$$;

revoke execute on function public.claim_founding_spot(bigint) from public, anon, authenticated;
grant execute on function public.claim_founding_spot(bigint) to service_role;
revoke execute on function public.next_subscription_invoice() from public, anon, authenticated;
grant execute on function public.next_subscription_invoice() to service_role;
revoke execute on function public.restaurant_plan_ok(bigint) from public, anon;
grant execute on function public.restaurant_plan_ok(bigint) to authenticated, service_role;

-- Restaurants approved before subscriptions existed are the first partners: they get the founding spots, oldest first.
insert into public.restaurant_subscriptions (restaurant_id, plan, status, founding_number, auto_renew, price_cents)
select id, 'founding', 'active', row_number() over (order by created_at, id), false, 0
from public.restaurants
where status = 'approved'
order by created_at, id
limit 50;

-- Why a restaurant can't post or turn on offers right now (null when it can).
create function public._restaurant_posting_block(rid bigint) returns text
language plpgsql stable security definer set search_path = public as $$
declare
  r public.restaurants;
begin
  select * into r from public.restaurants where id = rid;
  if r.status = 'banned' then
    return 'Your restaurant has been removed from Bite Wise, so you cannot post offers.';
  elsif r.status = 'suspended' then
    return 'Your restaurant is suspended' || coalesce(' until ' || to_char(r.suspended_until at time zone 'America/Los_Angeles', 'FMMonth FMDD'), '')
      || ', so you cannot post offers. Please contact Bite Wise support.';
  elsif r.status = 'approved' and not public.restaurant_plan_ok(rid) then
    return 'Choose a Bite Wise plan to post offers: open the Plan tab of your dashboard.';
  end if;
  return null;
end;
$$;
revoke execute on function public._restaurant_posting_block(bigint) from public, anon, authenticated;

-- As in 20261002000100_bite_wise_name.sql, with the new posting rules (bans, timed suspensions, plans).
create or replace function public.restaurant_save_offer(
  p_offer_id bigint, p_menu_item_id bigint, p_reason public.offer_reason, p_description text,
  p_discount_pct integer, p_quantity integer, p_expires_in_minutes integer
) returns public.offers
language plpgsql security definer set search_path = public as $$
declare
  rid bigint := public.my_restaurant_id();
  blocked text;
  item public.menu_items;
  existing public.offers;
  v public.offers;
  v_start timestamptz;
  v_end timestamptz;
  committed integer := 0;
  v_description text;
begin
  if rid is null then
    raise exception 'Restaurant profile not found.' using errcode = 'BB404';
  end if;
  blocked := public._restaurant_posting_block(rid);
  if p_offer_id is not null then
    select * into existing from public.offers where id = p_offer_id and restaurant_id = rid for update;
    if existing.id is null then
      raise exception 'Offer not found.' using errcode = 'BB404';
    end if;
    if existing.status = 'ended' then
      raise exception 'Ended offers cannot be edited.' using errcode = 'BB409';
    end if;
    committed := existing.quantity_total - existing.quantity_available;
  elsif blocked is not null then
    raise exception '%', blocked using errcode = 'BB403';
  end if;

  select * into item from public.menu_items where id = p_menu_item_id and restaurant_id = rid and active;
  if item.id is null then
    raise exception 'Menu item not found.' using errcode = 'BB404';
  end if;
  if p_reason is null then
    raise exception 'Please choose why this food is available.' using errcode = 'BB400';
  end if;
  if p_discount_pct is null or p_discount_pct < 1 or p_discount_pct > 90 then
    raise exception 'Discount must be a whole number from 1 to 90.' using errcode = 'BB400';
  end if;
  if p_quantity is null or p_quantity < 1 or p_quantity > 500 then
    raise exception 'Quantity must be a whole number from 1 to 500.' using errcode = 'BB400';
  end if;
  if p_quantity < committed then
    raise exception '% already ordered, so quantity cannot be lower than that.', committed using errcode = 'BB400';
  end if;
  if char_length(coalesce(p_description, '')) > 500 then
    raise exception 'Description must be at most 500 characters.' using errcode = 'BB400';
  end if;

  if p_expires_in_minutes is not null then
    if p_expires_in_minutes < 5 or p_expires_in_minutes > 4320 then
      raise exception 'Discard timer (minutes) must be a whole number from 5 to 4320.' using errcode = 'BB400';
    end if;
    v_start := case when existing.id is not null and existing.pickup_start < now() then existing.pickup_start else now() end;
    v_end := now() + make_interval(mins => p_expires_in_minutes);
  elsif existing.id is not null then
    v_start := existing.pickup_start;
    v_end := existing.pickup_end;
  else
    raise exception 'Please set the discard timer.' using errcode = 'BB400';
  end if;

  v_description := coalesce(nullif(btrim(p_description), ''), item.description);

  if existing.id is null then
    insert into public.offers (restaurant_id, menu_item_id, image_url, title, description, reason, dietary,
      original_price_cents, discount_pct, quantity_total, quantity_available, pickup_start, pickup_end)
    values (rid, item.id, item.image_url, item.name, v_description, p_reason, item.dietary,
      item.price_cents, p_discount_pct, p_quantity, p_quantity, v_start, v_end)
    returning * into v;
  else
    -- Price changes only affect new orders; existing orders keep the price they were quoted.
    update public.offers set menu_item_id = item.id, image_url = item.image_url, title = item.name,
      description = v_description, reason = p_reason, dietary = item.dietary, original_price_cents = item.price_cents,
      discount_pct = p_discount_pct, quantity_total = p_quantity, quantity_available = p_quantity - committed,
      pickup_start = v_start, pickup_end = v_end
    where id = existing.id
    returning * into v;
    update public.orders set pickup_end = v_end where offer_id = v.id and status in ('pending_payment', 'reserved');
  end if;
  return v;
end;
$$;

create or replace function public.restaurant_set_offer_status(p_offer_id bigint, p_status public.offer_status) returns public.offers
language plpgsql security definer set search_path = public as $$
declare
  v public.offers;
  blocked text;
begin
  select * into v from public.offers where id = p_offer_id and restaurant_id = public.my_restaurant_id() for update;
  if v.id is null then
    raise exception 'Offer not found.' using errcode = 'BB404';
  end if;
  if v.status = 'ended' then
    raise exception 'This offer has already ended.' using errcode = 'BB409';
  end if;
  if p_status = 'active' then
    if v.pickup_end <= now() then
      raise exception 'The pickup window has passed. Create a new offer.' using errcode = 'BB400';
    end if;
    blocked := public._restaurant_posting_block(v.restaurant_id);
    if blocked is not null then
      raise exception '%', blocked using errcode = 'BB403';
    end if;
  end if;
  update public.offers set status = p_status where id = v.id returning * into v;
  return v;
end;
$$;

-- As in 20261001000100_timed_suspensions_and_deletion.sql, plus: restaurants whose suspension has ended are
-- approved again, paid plans that ran out lapse, and live offers of restaurants without a plan are paused.
create or replace function public.sweep() returns jsonb
language plpgsql security definer set search_path = public as $$
declare
  x record;
  failed integer := 0;
  expired integer := 0;
  ended integer := 0;
  reactivated integer := 0;
  reinstated integer := 0;
  lapsed integer := 0;
begin
  for x in select id from public.orders where status = 'pending_payment' and created_at < now() - interval '15 minutes' loop
    perform public.release_order(x.id, 'pending_payment', 'failed', true);
    failed := failed + 1;
  end loop;
  for x in select id from public.orders where status = 'reserved' and pickup_end < now() - interval '10 minutes'
             and (capture_started_at is null or capture_started_at < now() - interval '5 minutes') loop
    perform public.release_order(x.id, 'reserved', 'expired', false);
    expired := expired + 1;
  end loop;
  update public.offers set status = 'ended' where status <> 'ended' and pickup_end < now();
  get diagnostics ended = row_count;
  delete from public.pin_failures where at < now() - interval '1 day';
  update public.profiles set status = 'active', suspended_until = null
    where status = 'suspended' and suspended_until <= now();
  get diagnostics reactivated = row_count;
  update public.restaurants set status = 'approved', suspended_until = null
    where status = 'suspended' and suspended_until <= now();
  get diagnostics reinstated = row_count;

  update public.restaurant_subscriptions set status = 'expired', updated_at = now()
    where plan <> 'founding' and status <> 'expired' and not public.restaurant_plan_ok(restaurant_id);
  get diagnostics lapsed = row_count;
  update public.offers o set status = 'paused'
    where o.status = 'active'
      and exists (select 1 from public.restaurants r where r.id = o.restaurant_id and r.status = 'approved')
      and not public.restaurant_plan_ok(o.restaurant_id);

  return jsonb_build_object('failed', failed, 'expired', expired, 'ended', ended, 'reactivated', reactivated,
    'reinstated', reinstated, 'lapsed', lapsed);
end;
$$;

-- The restaurant agreement now covers subscription fees and the customer terms permanent bans.
update public.legal_documents set version = '2026-10-06.1';
