-- Rescue Bites schema: accounts, restaurants, menus, offers, orders, payments, credit, payouts, legal.
-- Money is stored in integer cents; rates in basis points (1 bp = 0.01%).

create extension if not exists postgis with schema extensions;
create extension if not exists citext with schema extensions;

create type public.user_role as enum ('customer', 'restaurant', 'admin');
create type public.account_status as enum ('active', 'suspended');
create type public.restaurant_status as enum ('pending', 'approved', 'suspended');
create type public.offer_status as enum ('active', 'paused', 'ended');
create type public.offer_reason as enum ('wrong_order', 'delayed_order', 'unclaimed_order', 'overproduction', 'end_of_day', 'other');
create type public.order_status as enum ('pending_payment', 'reserved', 'picked_up', 'cancelled', 'expired', 'failed');
create type public.refund_method as enum ('original', 'credit');
create type public.credit_kind as enum ('refund', 'goodwill', 'redeem', 'restore', 'adjustment');
create type public.payout_kind as enum ('transfer', 'reversal', 'manual');

-- ---------------------------------------------------------------- accounts

-- One row per Supabase Auth user. Created by the on_auth_user_created trigger.
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email extensions.citext not null unique,
  username extensions.citext not null unique check (username::text ~ '^[A-Za-z0-9_.]{3,24}$'),
  role public.user_role not null default 'customer',
  status public.account_status not null default 'active',
  stripe_customer_id text,
  created_at timestamptz not null default now()
);

-- Business settings the owner can change in the admin console.
create table public.settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);
insert into public.settings (key, value) values
  ('service_fee_bps', '500'),
  ('default_tax_rate_bps', '1035'),
  ('require_restaurant_approval', 'true'),
  ('tax_service_fee', 'false');

-- Current version of each legal document. Must match src/lib/legal/documents.ts
-- (a test checks this). Bump both when the text changes; users then re-accept.
create table public.legal_documents (
  id text primary key,
  title text not null,
  version text not null,
  roles public.user_role[] not null
);
insert into public.legal_documents (id, title, version, roles) values
  ('customer-terms', 'Customer Terms of Service', '2026-09-29.1', '{customer}'),
  ('restaurant-agreement', 'Restaurant Partner Agreement', '2026-09-29.1', '{restaurant}'),
  ('privacy', 'Privacy Policy', '2026-09-29.1', '{customer,restaurant}');

create table public.terms_acceptances (
  id bigint generated always as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  document text not null references public.legal_documents (id),
  version text not null,
  accepted_at timestamptz not null default now(),
  ip text not null default '',
  user_agent text not null default ''
);
create index terms_acceptances_user_idx on public.terms_acceptances (user_id, document, version);

-- ---------------------------------------------------------------- service area

-- Puget Sound ZIP codes with center points (USPS ZIP list; coordinates from GeoNames, CC BY 4.0).
create table public.zips (
  zip text primary key check (zip ~ '^\d{5}$'),
  city text not null,
  cities text[] not null,
  county text not null,
  location extensions.geography(point, 4326) not null
);
create index zips_city_idx on public.zips (lower(city));

-- ---------------------------------------------------------------- restaurants

create table public.restaurants (
  id bigint generated by default as identity primary key,
  owner_id uuid not null unique references public.profiles (id) on delete cascade,
  name text not null check (char_length(name) between 2 and 80),
  description text not null default '' check (char_length(description) <= 400),
  cuisine text not null default '' check (char_length(cuisine) <= 40),
  address text not null check (char_length(address) between 3 and 120),
  city text not null check (char_length(city) between 2 and 60),
  zip text not null check (zip ~ '^\d{5}(-\d{4})?$'),
  phone text not null default '' check (char_length(phone) <= 30),
  location extensions.geography(point, 4326),
  lat double precision generated always as (extensions.st_y(location::extensions.geometry)) stored,
  lng double precision generated always as (extensions.st_x(location::extensions.geometry)) stored,
  tax_rate_bps integer not null check (tax_rate_bps between 0 and 2000),
  status public.restaurant_status not null default 'pending',
  admin_note text not null default '',
  created_at timestamptz not null default now()
);
create index restaurants_location_idx on public.restaurants using gist (location);
create index restaurants_status_idx on public.restaurants (status);

-- Stripe Connect account for payouts. Only the owner and admins can read it; only the server writes it.
create table public.restaurant_payment_accounts (
  restaurant_id bigint primary key references public.restaurants (id) on delete cascade,
  stripe_account_id text unique,
  charges_enabled boolean not null default false,
  payouts_enabled boolean not null default false,
  details_submitted boolean not null default false,
  bank_summary text not null default '',
  updated_at timestamptz not null default now()
);

create table public.menu_items (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  name text not null check (char_length(name) between 2 and 80),
  description text not null default '' check (char_length(description) <= 500),
  price_cents integer not null check (price_cents between 50 and 100000),
  dietary text[] not null default '{}',
  image_url text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index menu_items_restaurant_idx on public.menu_items (restaurant_id, active);

-- ---------------------------------------------------------------- offers

-- A discounted menu item with a discard timer (pickup_end).
create table public.offers (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  menu_item_id bigint references public.menu_items (id),
  image_url text,
  title text not null,
  description text not null default '' check (char_length(description) <= 500),
  reason public.offer_reason not null,
  dietary text[] not null default '{}',
  original_price_cents integer not null check (original_price_cents > 0),
  discount_pct integer not null check (discount_pct between 1 and 90),
  price_cents integer generated always as
    ((floor((original_price_cents * (100 - discount_pct))::numeric / 100 + 0.5))::integer) stored,
  quantity_total integer not null check (quantity_total between 1 and 500),
  quantity_available integer not null check (quantity_available >= 0 and quantity_available <= quantity_total),
  pickup_start timestamptz not null default now(),
  pickup_end timestamptz not null,
  status public.offer_status not null default 'active',
  created_at timestamptz not null default now(),
  check (pickup_end > pickup_start)
);
create index offers_live_idx on public.offers (status, pickup_end);
create index offers_restaurant_idx on public.offers (restaurant_id, status);

-- ---------------------------------------------------------------- payments & orders

-- Saved cards. Only brand, last 4 and expiry are stored; the card itself lives with Stripe.
create table public.payment_methods (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id) on delete cascade,
  provider_ref text not null,
  brand text not null,
  last4 text not null check (last4 ~ '^\d{4}$'),
  exp_month integer not null check (exp_month between 1 and 12),
  exp_year integer not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);
create index payment_methods_user_idx on public.payment_methods (user_id);

-- Order lifecycle: pending_payment -> reserved -> picked_up
--                                  \-> failed    \-> cancelled | expired
create table public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles (id),
  offer_id bigint not null references public.offers (id),
  restaurant_id bigint not null references public.restaurants (id),
  customer_username text not null,
  item_title text not null,
  image_url text,
  quantity integer not null check (quantity > 0),
  unit_price_cents integer not null,
  original_unit_price_cents integer not null,
  discount_pct integer not null,
  subtotal_cents integer not null,
  service_fee_cents integer not null,
  service_fee_bps integer not null,
  tax_rate_bps integer not null,
  tax_cents integer not null,
  total_cents integer not null,
  status public.order_status not null default 'pending_payment',
  payment_ref text,
  card_label text not null default '',
  -- Stripe Connect: destination account used when the card was authorized (null = charged on the platform).
  destination_account text,
  pickup_end timestamptz not null,
  created_at timestamptz not null default now(),
  picked_up_at timestamptz,
  closed_at timestamptz,
  capture_started_at timestamptz,
  -- Set when an order is released but its card hold still has to be voided with the payment provider.
  needs_void boolean not null default false,
  -- Refunds: refunded_cents = back to the ORIGINAL payment (the restaurant and Rescue Bites give up that share);
  -- credited_cents = issued as Rescue Bites PLATFORM CREDIT (funded by Rescue Bites, restaurant keeps its money).
  refunded_cents integer not null default 0,
  card_refunded_cents integer not null default 0,
  credited_cents integer not null default 0,
  credit_applied_cents integer not null default 0 check (credit_applied_cents >= 0),
  refunded_at timestamptz,
  refund_reason text not null default ''
);
create index orders_user_idx on public.orders (user_id, created_at desc);
create index orders_restaurant_idx on public.orders (restaurant_id, status);
create index orders_picked_up_idx on public.orders (picked_up_at) where status = 'picked_up';
create index orders_offer_idx on public.orders (offer_id, status);

-- Pickup PINs are kept apart from orders so restaurants can never read them: they must type the
-- PIN the customer shows them. Active PINs are unique per restaurant.
create table public.order_pins (
  order_id bigint primary key references public.orders (id) on delete cascade,
  restaurant_id bigint not null references public.restaurants (id),
  pin text not null check (pin ~ '^\d{4}$'),
  active boolean not null default true
);
create unique index order_pins_active_idx on public.order_pins (restaurant_id, pin) where active;

-- Failed PIN lookups, to rate-limit guessing (4 digits is guessable by brute force).
create table public.pin_failures (
  id bigint generated always as identity primary key,
  restaurant_id bigint not null references public.restaurants (id) on delete cascade,
  at timestamptz not null default now()
);
create index pin_failures_idx on public.pin_failures (restaurant_id, at);

create table public.refunds (
  id bigint generated always as identity primary key,
  order_id bigint not null references public.orders (id),
  amount_cents integer not null check (amount_cents > 0),
  method public.refund_method not null,
  card_cents integer not null default 0,
  credit_cents integer not null default 0,
  restaurant_share_cents integer not null default 0,
  reason text not null,
  provider_ref text,
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);
create index refunds_order_idx on public.refunds (order_id);

-- Platform credit ledger. Balance = sum(amount_cents). Positive = issued/restored, negative = used.
create table public.credit_ledger (
  id bigint generated always as identity primary key,
  user_id uuid not null references public.profiles (id),
  amount_cents integer not null check (amount_cents <> 0),
  kind public.credit_kind not null,
  order_id bigint references public.orders (id),
  note text not null default '',
  created_by uuid references public.profiles (id),
  created_at timestamptz not null default now()
);
create index credit_ledger_user_idx on public.credit_ledger (user_id);

-- Money sent to restaurants: Stripe Connect transfers (one per completed order), reversals for
-- refunds, and manual payouts. Invoice numbers and transaction details are assigned by the system.
create table public.payouts (
  id bigint generated by default as identity primary key,
  restaurant_id bigint not null references public.restaurants (id),
  order_id bigint references public.orders (id),
  kind public.payout_kind not null,
  amount_cents integer not null check (amount_cents <> 0),
  invoice_number text unique,
  transaction_id text not null default '',
  bank_details text not null default '',
  note text not null default '',
  created_by uuid references public.profiles (id),
  paid_at timestamptz not null default now()
);
create index payouts_restaurant_idx on public.payouts (restaurant_id, paid_at desc);

create table public.audit_log (
  id bigint generated always as identity primary key,
  admin_id uuid references public.profiles (id),
  action text not null,
  target_type text not null,
  target_id text,
  details text not null default '',
  created_at timestamptz not null default now()
);
